name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Get access to OCIR
        id: get-ocir
        uses: oracle-actions/get-ocir-repository@v1.0
        with:
          name: ${{ secrets.OCI_DOCKER_REPO }}
          compartment: ${{ secrets.OCI_COMPARTMENT_OCID }}
      
      - name: Log into OCIR
        uses: oracle-actions/login-ocir@v1.0
        id: login-ocir
        with:
          auth_token: ${{ secrets.OCI_AUTH_TOKEN }}
      
      - name: docker build
        id: docker-build
        run: |
          docker build -t ${{ secrets.OCI_DOCKER_REPO }}:${{ github.sha }} .
      
      - name: docker push
        id: docker-push
        run: |
          docker push ${{ secrets.OCI_DOCKER_REPO }}:${{ github.sha }}
      
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.PAT }}
          repository: ${{ github.actor }}/argocd-node-app-config
          event-type: new-image
          client-payload: '{"image": "${{ secrets.OCI_DOCKER_REPO }}:${{ github.sha }}"}'
